<?php

return [
    'name' => 'Task',
    'SEED_TASK_BOARD_TASKS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_TASK_BOARDS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_TASK_CATEGORIES_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_TASK_COMMENT_VOTES_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_TASK_COMMENTS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_TASK_HISTORIES_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_TASK_HISTORY_TYPES_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_TASK_TAGS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_TASK_WORKS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_TASKS_COUNT' => env('SEEDER_DEFAULT', 3),
];
